name = "hpi-onboarding"
main = "worker.js"
compatibility_date = "2024-11-01"
account_id = "d2586c55db329e1e12cbaf3285d32f1a"

[[d1_databases]]
binding = "DB"
database_name = "hpi-portal"
database_id = "31c09424-3d8d-4f9e-9325-100d85ede480"

[vars]
FROM_EMAIL = "connect@healthplusint.com.au"
SITE_URL = "https://healthplusint.com.au"
